### ISSUE TITLE
Review default data path

### ISSUE THREAD

**Issue by alberpilot** [Achiefs/fim#15]
The default configuration contains:
```
log:
  output:
    file: /var/log/fim/fim.log
    # Possible levels debug, info, error, warning
    level: debug
  events:
    file: /usr/share/fim/events.json
    # Format of output events options json/syslog
    format: json
```
Maybe it could be a good idea to review if `/usr/share/fim/` is the best default place where to store the produced data instead of `/var/lib` for instance.
