### ISSUE TITLE
Add possibility to ignore multiply file extensions

### ISSUE THREAD

**Issue by famouzkk** [Achiefs/fim#26]
Please let ignore argument to be an array, eg. 
```yaml
monitor: 
  - path: /tmp/dir
    ignore: [.txt, .log, .js]
```
or regex, to give us option to ignore multiple files. Thanks.
